#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_OP_MI_R3G

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron: 0 10 * * *
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment | 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "工作流运行于：$(lsb_release -d)"
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code | 克隆源代码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt

    - name: Import external feeds - small-package | 克隆 small-package 库
      working-directory: ./openwrt
      run: |
        git clone https://github.com/lrst6963/small-package package/small-package     
  
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: change config | 更改配置
      working-directory: ./openwrt
      run: |
        sed -i 's/hostname='"'"'OpenWrt'"'"'/hostname='"'"'Mi_R3G'"'"'/g' package/base-files/files/bin/config_generate
        sed -i 's/lan) ipad=${ipaddr:-"192.168.1.1"} ;;/lan) ipad=${ipaddr:-"192.168.168.1"} ;;/g' package/base-files/files/bin/config_generate

    - name: Configuration Customization - Build_OP_MI_R3G | 配置定制
      env:
        CONFIG_FILE: 'config/Mi_R3G.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
        cat .config
        
    - name: Download package | 下载引用库
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)


    - name: Build firmware | 编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) || make -j$(nproc) 
        if [ $? -ne 0 ];then
          echo "Build Error!"
          exit 127
        else
          echo "Build Done!"
          exit 0
        fi


    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_Mi_R3G
        path: openwrt/bin


    - name: Upload To Transfer.sh
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      working-directory: ./openwrt
      run: |
        ZIP_FILE_NAME="openwrt-ramips-mt7621-xiaomi_mi-router-3g-$(date +%Y%m%d%H%M).zip"
        zip -r $ZIP_FILE_NAME ./bin/*
        curl -sX GET "http://www.pushplus.plus/send?token=${{ secrets.PUSHPLUS_TOKEN }}&title=OpenWrt%20Build%20R3G%20&content=%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5%EF%BC%9A$(curl --upload-file ./$ZIP_FILE_NAME https://transfer.sh/$ZIP_FILE_NAME)&template=html" > /dev/null


    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 0
